### PR TITLE
Removing "Biological Entity part of cellular organism"

### PR DESCRIPTION
**Pull request by matentzn**
@balhoff suggested this may be over constrained.

https://github.com/monarch-initiative/monarch-ontology/issues/33

### CODE REVIEW

**Comment by balhoff** [comment]
There is a comment on this term mentioning Darwin Core. Maybe @ramonawalls should also take a look?

**Comment by ramonawalls** [comment]
I think the comment should be removed from CARO, because this term does not align with DwC:Organism ("A particular organism or defined group of organisms considered to be taxonomically homogeneous."). We already have a term in PCO called `organismal entity` (http://purl.obolibrary.org/obo/PCO_0000031) which we use in BCO to map to Organism (currently Organism subClassOf 'organismal entity', but I'm not sure why it is not Organism equivalent to 'organismal entity').

**Comment by cmungall** [comment]
I agree, and with COB now existing, maybe we can obsolete biological entity in CARO?

**Review by dosumis — APPROVED** [review]

**Comment by matentzn** [comment]
Thank you everyone, please capture your own comments in issues, as they will be forgotten as part of this PR.

**Pull request merged**
